name: apiary_app
description: Un'app per la gestione degli apiari.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  intl: 0.19.0
  sqflite: ^2.3.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.1
  image_picker: ^1.0.4
  package_info_plus: ^4.1.0
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.0.0
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  fl_chart: ^0.63.0
  flutter_riverpod: ^2.0.0 # Ensure you have the latest version or the one you're using
  flutter_local_notifications_linux: ^4.0.0+1
  flutter_speed_dial: ^7.0.0
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  share_plus: ^8.0.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFC107"
  adaptive_icon_foreground: "assets/icons/icon.png"  # Stesso file
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#FFC107"
    theme_color: "#FFA000"

