name: Apiary_app
description: Un'app per la gestione degli apiari.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.1
  image_picker: ^1.0.4
  package_info_plus: ^4.1.0
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.0
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  share_plus: ^7.1.0
  fl_chart: ^0.63.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700